namespace Template {

    export let sound = {
        // music 
        wakeUp: "./Music/CombinedMusicMedium.wav",
        adventure: "./Music/Adventure.mp3",
        forestWalk: "./Music/ForestWalk.mp3",
        illusoryRealm: "./Music/IllusoryRealm.mp3",
        keysOfMoon: "./Music/keysOfMoonWhitePetals.mp3",

        // sound
        city: "./SoundEffects/ambience_city_london_uk_sirens_distant_constant_construction_pounding_wind_trees.mp3",
        rain1: "./SoundEffects/rain-03.mp3",
        rain2: "./SoundEffects/rain-06.mp3",
        rain3: "./SoundEffects/rain-07.mp3",
        crow: "./SoundEffects/Blastwave_FX_BirdCrowCawMultiple_SFXB.17.mp3",
        storm: "./SoundEffects/zapsplat_nature_ambience_approaching_thunderstorm_rain_wind_intensifies_blustery_rumbles_thunder_74166.mp3",
        wind1: "./SoundEffects/wind-breeze-01.mp3",
        wind2: "./SoundEffects/windy-forest-ambience-01.mp3",
        thunderStorm1: ".SoundEffects/zapsplat_nature_thunderstorm_approaching_distant_rumbles_rain_then_rain_heavier_at_2m50s_57911.mp3",
        thunderStorm2: "./SoundEffects/zapsplat_nature_rain_thunderstorm_close_rain_drips_yard_57904.mp3",
        dogBark1: "./SoundEffects/zapsplat_animals_dog_labrador_bark_slight_distance_echo_neighbourhood_11751.mp3",
        springWeather: "./SoundEffects/spring-weather-1.wav",
        springBirds: "./SoundEffects/Blastwave_FX_NatureBirdsCrickets_BW.1500.mp3",
        pageFlip: "./SoundEffects/page-flip-02.mp3",

        //voice over
        s1: "./VoiceOver/S1.wav",
        s2: "./VoiceOver/S2.wav",
        s3_1: "./VoiceOver/S3.1.wav",
        s3_2: "./VoiceOver/S3.2.wav",
        s3_3: "./VoiceOver/S3.3.wav",
        s3_3_Choices: "./VoiceOver/S3.3_Choices.wav",
        s3_4_iInsult: "./VoiceOver/S3.4_iInsult.wav",
        s3_4_iInsult2: "./VoiceOver/S3.4_iInsult2.wav",
        s3_4_iSayHelp: "./VoiceOver/S3.4_iSayHelp.wav",
        s4A_1: "./VoiceOver/S4A.1.wav",
        s4A_2: "./VoiceOver/S4A.2.wav",
        s4A_3: "./VoiceOver/S4A.3.wav",
        s4A_3_Choices: "./VoiceOver/S4A.3_Choices.wav",
        S4A_4_iBeAngry: "./VoiceOver/S4A.4_iBeAngry.wav",
        S4A_4_iBeNice: "./VoiceOver/S4A.4_iBeNice.wav",
        s4B_1: "./VoiceOver/S4B.1.wav",
        s4B_2: "./VoiceOver/S4B.2.wav",
        s4B_3: "./VoiceOver/S4B.3.wav",
        s4B_3_Choices: "./VoiceOver/S4B.3_Choices.wav",
        s4B_4_iSayNo: "./VoiceOver/S4B.4_iSayNo.wav",
        s5B_1: "./VoiceOver/S5B.1.wav",
        s5B_2: "./VoiceOver/S5B.2.wav",
        s5B_2_Choices: "./VoiceOver/S5B.2_Choices.wav",
        s5B_3_iSayNotSorry: "./VoiceOver/S5B.3_iSayNotSorry.wav",
        s5B_3_iSaySorry: "./VoiceOver/S5B.3_iSaySorry.wav",
        s5C_1: "./VoiceOver/S5C.1.wav",
        s5C_2: "./VoiceOver/S5C.2.wav",
        s6A: "./VoiceOver/S6A.wav",
        s7A_1: "./VoiceOver/S7A.1.wav",
        s7A_2: "./VoiceOver/S7A.2.wav",
        s7A_3: "./VoiceOver/S7A.3.wav",
        s7A_4: "./VoiceOver/S7A.4.wav",
        s7A_5: "./VoiceOver/S7A.5.wav",
        s7C_1: "./VoiceOver/S7C.1.wav",
        s7C_2: "./VoiceOver/S7C.2.wav",
        s7C_2_2: "./VoiceOver/S7C.2_2.wav",
        s7C_3: "./VoiceOver/S7C.3.wav",
        s8_1: "./VoiceOver/S8.1.wav",
        s8_2: "./VoiceOver/S8.2.wav",
        s8_3: "./VoiceOver/S8.3.wav",
        s8_3_Choices: "./VoiceOver/S8.3_Choices.wav",
        s9A_1: "./VoiceOver/S9A.1.wav",
        s9A_2: "./VoiceOver/S9A.2.wav",
        s9A_3: "./VoiceOver/S9A.3.wav",
        s9A_4: "./VoiceOver/S9A.4.wav",
        s9A_5: "./VoiceOver/S9A.5.wav",
        s9A_5_Choices: "./VoiceOver/S9A.5_Choices.wav",
        s9B_1: "./VoiceOver/S9B.1.wav",
        s9B_2: "./VoiceOver/S9B.2.wav",
        s9B_3: "./VoiceOver/S9B.3.wav",
        s9B_4: "./VoiceOver/S9B.4.wav",
        s10A_1: "./VoiceOver/S10A.1.wav",
        s10A_2: "./VoiceOver/S10A.2.wav",
        s10A_3: "./VoiceOver/S10A.3.wav",
        s10A_4: "./VoiceOver/S10A.4.wav",
        s10A_5: "./VoiceOver/S10A.5.wav",
        s10B_1: "./VoiceOver/S10B.1.wav",
        s10B_2: "./VoiceOver/S10B.2.wav",
        s10B_3: "./VoiceOver/S10B.3.wav",
        s10B_4: "./VoiceOver/S10B.4.wav",
        s10B_5: "./VoiceOver/S10B.5.wav",
        startAgainScreen: "./VoiceOver/StartAgainScreen.wav",
        badEnding: "./VoiceOver/BadEnding.wav",
        goodEnding: "./VoiceOver/GoodEnding.wav"

    };

}